### ISSUE TITLE
[Design] 친구짐 및 상세 페이지 구현

### ISSUE THREAD

**Issue by VronzeWook** [frankwon11/PickPack#20]
## 🛠 Issue

친구짐 및 상세 페이지 구현

## 📝 To-do

- [ ] 친구짐 목록 화면 구현
- [ ] 친구짐 상세 페이지 구현
- [ ] 친구가 없는 빈페이지 구현
