### ISSUE TITLE
[Design] 내 짐리스트(MyItemView) 구현

### ISSUE THREAD

**Issue by poetic-form** [frankwon11/PickPack#22]
## 🛠 Issue
MyItemView 그릴거에용

## 📝 To-do

- [ ] 선택된 짐이 없을 경우
- [ ] 선택된 짐들 보이기
- [ ] 내가 챙ㅇ길 공유짐 보이기
